// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using flight_data_server.Database;

#nullable disable

namespace flight_data_server.Migrations.AirlinerDB
{
    [DbContext(typeof(AirlinerDBContext))]
    [Migration("20230315040959_add_airliners2")]
    partial class add_airliners2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("flight_data_server.Models.Airliner.Airliner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AirlinerCallSign")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AirlinerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Airliner");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AirlinerCallSign = "THY",
                            AirlinerName = "Turkish Airliner"
                        },
                        new
                        {
                            Id = 2,
                            AirlinerCallSign = "UAE",
                            AirlinerName = "Emirates"
                        },
                        new
                        {
                            Id = 3,
                            AirlinerCallSign = "SIA",
                            AirlinerName = "Singapore Airlines"
                        },
                        new
                        {
                            Id = 4,
                            AirlinerCallSign = "ACA",
                            AirlinerName = "Air Canada"
                        },
                        new
                        {
                            Id = 5,
                            AirlinerCallSign = "UAL",
                            AirlinerName = "United Airlines"
                        },
                        new
                        {
                            Id = 6,
                            AirlinerCallSign = "DAL",
                            AirlinerName = "Delta Air Lines"
                        },
                        new
                        {
                            Id = 7,
                            AirlinerCallSign = "AAL",
                            AirlinerName = "American Airlines"
                        },
                        new
                        {
                            Id = 8,
                            AirlinerCallSign = "BAW",
                            AirlinerName = "British Airways"
                        },
                        new
                        {
                            Id = 9,
                            AirlinerCallSign = "DLH",
                            AirlinerName = "Lufthansa"
                        },
                        new
                        {
                            Id = 10,
                            AirlinerCallSign = "AFR",
                            AirlinerName = "Air France"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
