// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using flight_data_server.Database;

#nullable disable

namespace flight_data_server.Migrations.FlightDataDB
{
    [DbContext(typeof(FlightDataDBContext))]
    [Migration("20230315035414_add_flight_code")]
    partial class add_flight_code
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("flight_data_server.Models.FlightData.FlightData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("AOA")
                        .HasColumnType("float");

                    b.Property<int>("AirlinerID")
                        .HasColumnType("int");

                    b.Property<double>("Altitude")
                        .HasColumnType("float");

                    b.Property<int>("FlightCode")
                        .HasColumnType("int");

                    b.Property<double>("GroundSpeed")
                        .HasColumnType("float");

                    b.Property<double>("Heading")
                        .HasColumnType("float");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<DateTime>("LoggingTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<double>("Throttle")
                        .HasColumnType("float");

                    b.Property<double>("Throttle1")
                        .HasColumnType("float");

                    b.Property<double>("Throttle2")
                        .HasColumnType("float");

                    b.Property<double>("TrueAirSpeed")
                        .HasColumnType("float");

                    b.Property<int>("landingGear")
                        .HasColumnType("int");

                    b.Property<double>("outsideTemperature")
                        .HasColumnType("float");

                    b.Property<double>("totalFuel")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("FlightData");
                });
#pragma warning restore 612, 618
        }
    }
}
